name: Build and Release

on:
  push:
    branches: main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    name: Create the release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Clone
        uses: actions/checkout@v3
      
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest # Tag that triggered the workflow
          release_name: Latest
          body: "What's new?"
          draft: false
          prerelease: false
      
      - name: Build
        id: upload
        run:
          bash build.sh

      - name: Upload Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create-release.outputs.upload_url}}
          asset_path: ./config.sh
          asset_name: config.sh
          asset_content_type: application/octet-stream
        